# Generated by Django 5.2.6 on 2025-09-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0003_alter_people_created_alter_people_updated_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
    ]
