# Generated by Django 5.2.6 on 2025-09-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_alter_people_table_alter_planet_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planet',
            new_name='Planets',
        ),
        migrations.AlterModelTable(
            name='people',
            table=None,
        ),
        migrations.AlterModelTable(
            name='planets',
            table=None,
        ),
    ]
