# Generated by Django 5.2.6 on 2025-09-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0002_alter_people_homeworld'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='ex09_people',
        ),
        migrations.AlterModelTable(
            name='planet',
            table='ex09_planets',
        ),
    ]
